### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by chuckamus-prime** [fumitoito/angular-draggable#12]
I open the example, but nothing is draggable.

**Comment by fumitoito** [comment]
hi @chuckamus-prime , do you run `bower install` at the root of this component before you open the example ?

**Comment by chuckamus-prime** [comment]
No, Just my opinion, but an example html file should not require bower at all. If this is a requirement though, can it be stated somewhere?

**Comment by ghost** [comment]
I understand what you say but I'm not interested in how to prepare example.
So i remove exmple directory and [move it to Plunker](http://plnkr.co/edit/7sADZkqVI6LIUIixTwns?p=preview) to show example. please see it.

thanks.
